---
services:
  remmina:
    image: ghcr.io/vincentvc168/remmina:latest
    container_name: remmina
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    security_opt:
    - seccomp=unconfined
